name: "FiveDemandsNotOneLess"
version: "0.0.1"
author: "dawn"
main: "me.lkp111138.plugin.Main"
api-version: "1.12.2"
website: "https://google.com"
commands:
  test:
    description: "Five demands not one less"
    usage: "\u00a7cUsage: /fdnol word-1 word-2 word-3 word-4 word-5"
