name: "FiveDemandsNotOneLess"
version: "0.0.1"
author: "dawn"
main: "me.lkp111138.plugin.Main"
api-version: "1.12.2"
website: "https://google.com"
commands:
  fdnol:
    description: "Five demands not one less"
    usage: "\u00a7cUsage: /fdnol word-1 word-2 word-3 word-4 word-5"
  customitem:
    description: "Give the player a predefined custom item"
    usage: "\u00a7cUsage: /customitem ITEM_ID"
    aliases:
      - ci
  npc:
    description: "Info about NPCs"
    usage: "\u00a7cUsage: /npc <subcommand> [args...]"
  custommob:
    description: "Spawns a custom mob"
    usage: "\u00a7cUsage: /custommob spawn MOB_ID"
    aliases:
      - cm
  chestgui:
    description: "Opens a chest GUI"
    usage: "\u00a7cUsage: /chestgui"
    aliases:
      - gui